# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'marvelapp' do
  use_frameworks!

  # Pods for marvelapp
    pod 'Firebase/Analytics'
    pod 'Firebase/Core'
    pod 'Firebase/Auth'
    pod 'FirebaseUI/Auth'
    pod 'FirebaseUI/Email'
end
